runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: helloworld.php
- url: /api/sampleapi.php
  script: api/sampleapi.php
- url: /api/mail_multi_send.php
  script: api/mail_multi_send.php
- url: /api/mail_multi_send_check.php
  script: api/mail_multi_send_check.php
- url: /api/test_domain.php
  script: api/test_domain.php
